jobs:
  include:
    - dist: xenial
      group: dev
      script:
      - pyenv install --list
    - dist: bionic
      group: dev
      script:
      - pyenv install --list
    - dist: focal
      group: dev
      script:
      - pyenv install --list
