os: linux
dist: xenial

script:
- sudo apt-get update -yqq
- sudo apt-get upgrade -yqq
- sudo apt install ca-certificates openssl
- sudo update-ca-certificates
- curl https://asset-packagist.org/packages.json