jobs:
  - os: linux
    dist: xenial
    group: dev
    script:
      - pyenv versions
      - pip install -U pip
  - os: linux
    python: 3.7
    dist: xenial
    env:
      - PYTHONPATH=.
    script:
      - pyenv versions
      - pip install -U pip