jobs:
  include:
    - dist: xenial
      group: dev
      script:
      - pyenv instal --list
    - dist: bionic
      group: dev
      script:
      - pyenv instal --list
    - dist: focal
      group: dev
      script:
      - pyenv instal --list
