language: java

before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  - stage: 🚫 jdk.java.net - Archived OpenJDK General-Availability Releases
    env: JDK=8 🚫
    script: source ./install-jdk.sh --feature 8

after_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version