language: python
python:
  - "3.7"

group: dev

install:

  - pip install .
  - pip install -r tests/requirements.txt

env:
- PYTHONPATH=.



# command to run tests
script:
  - curl -sSf --retry 5 -o python-3.7.2.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.7.2.tar.bz2
  - sudo tar xjf python-3.7.2.tar.bz2 --directory /
  - python -m pip --version
  - python -Werror tests/smoke_test.py
  - python -m unittest discover tests

