jobs:
  - os: linux
    dist: xenial
    group: dev
    script:
      - pyenv versions
      - pip install -U pip
  - os: linux
    python: 3.7
    dist: xenial
    env:
      - PYTHONPATH=.
    script:
      - python -V
      - python -m pip --version
      - pyenv install -v 3.7.2
      - python -V
      - python -m pip --version
      - pyenv versions
      - pip install -U pip