---
jobs:
  - os: linux
    dist: xenial
    group: dev
    script:
      - pyenv versions
      - pip install -U pip
  - os: linux
    dist: xenial
    group: stable
    script:
      - pyenv versions
      - pip install -U pip

