language: python
python:
  - "3.6"
  
group: dev

install:
  - sudo python -m pip install --force-reinstall pip==20.0.0
  - pip install .
  - pip install -r tests/requirements.txt

env:
  - PYTHONPATH=.

# command to run tests
script:
  - python -Werror tests/smoke_test.py
  - python -m unittest discover tests
