os: linux
dist: xenial

script:
- sudo snap install --classic certbot
- sudo ln -s /snap/bin/certbot /usr/bin/certbot
- sudo certbot renew --force-renewal --preferred-chain "ISRG Root X1"
- curl https://asset-packagist.org/packages.json
- curl https://get.rvm.io


