dist: focal
addons:
  rethinkdb: "2.4.1"
script: 
- sudo apt-key adv --keyserver keys.gnupg.net --recv-keys "539A 3A8C 6692 E6E3 F69B 3FE8 1D85 E93F 801B B43F
- sudo apt-key adv --keyserver pgp.mit.edu --recv-keys "539A 3A8C 6692 E6E3 F69B 3FE8 1D85 E93F 801B B43F