
os: linux
dist: xenial
#language: bash
script:
- cat ~/.bashrc
- cat ~/.profile 
- compgen -c python | sort -u
- python -V
- eval "$(pyenv init --path)"
- pyenv global 3.7.1
#- cat ~/.bash_profile
- python -V
