language: python
python:
  - "3.7"

group: dev
before_install:
  - pip install virtualenv --upgrade

install:
  - apt install python3.7
  - pip install .
  - pip install -r tests/requirements.txt

env:
- PYTHONPATH=.



# command to run tests
script:
  - python -Werror tests/smoke_test.py
  - python -m unittest discover tests
