os: linux
dist: xenial

script:
# - sudo rm /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
# - sudo update-ca-certificates
- sudo apt-get update
- sudo apt-get install libgnutls-openssl27
- curl -i https://asset-packagist.org/packages.json
- curl -i https://get.rvm.io
- curl -i https://cmake.org/files


