dist: bionic
sudo: required
arch: s390x
services:
- docker
before_install:
- mkdir -vp ~/.docker/cli-plugins/
- curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-s390x" > ~/.docker/cli-plugins/docker-buildx
- chmod a+x ~/.docker/cli-plugins/docker-buildx
- cd /etc/docker
- sudo echo ""exec-opts":["native.cgroupdriver=systemd"]" > daemon.json && cat daemon.json
- cd ..
- sudo service docker restart
- docker info && sudo apt-get install linux-image-$(uname -r) socat -y
- sudo sysctl net.ipv6.conf.all.disable_ipv6=1
- sudo sysctl net.ipv6.conf.default.disable_ipv6=1
- sudo sysctl net.ipv6.conf.lo.disable_ipv6=1
- sudo sysctl -p && sudo systemctl enable docker.service && sudo systemctl restart docker
- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
- sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
- sudo swapoff -a && sudo apt-get install -y kubelet kubeadm kubectl
- sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --v=5
- mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
- sudo chown $(id -u):$(id -g) $HOME/.kube/config
- sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
- sudo kubectl taint nodes --all node-role.kubernetes.io/master- && sudo kubectl get nodes

install:
- kubectl get pods --all-namespaces
env:
  global:
  - DOCKER_REGISTRY=docker.io
  - DOCKER_BUILD_ARGS="-q"
