jobs:
 - os: linux
    language: python
    python: 3.7
    dist: xenial
    env:
      - PYTHONPATH=.
    script:
      - python -V
      - python -m pip --version
      - pyenv global 3.7.1
      - python -V
      - pip install --user pip
      - python -m pip --version
      - pyenv versions
      - pip install -U pip