
os: linux
dist: xenial
group: dev
script:
- pyenv versions
- python -V
- which python
- echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
- echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
- echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
- echo 'eval "$(pyenv init --path)"' >> ~/.profile
- echo 'eval "$(pyenv init -)"' >> ~/.bashrc
- exec "$SHELL"
- pyenv global 3.7.1
- python -V
- which python
