
os: linux
dist: xenial
#language: bash
script:
- cat ~/.bashrc
- cat ~/.profile
- cat ~/.bash_profile.d
- compgen -c python | sort -u
- python -V
- eval "$(pyenv init -)"
- pyenv global 3.7.1
#- cat ~/.bash_profile
- python -V
