version: ~> 1.0
language: cpp
dist: focal
osx_image: xcode12.2

cache:
  - ccache
  - directories:
      - $TRAVIS_BUILD_DIR/vcpkg
      - $HOME/.cache/vcpkg/archives

addons:
  apt:
    packages:
      - build-essential
      - automake
      - autoconf
      - autoconf-archive
      - libtool-bin
      - texinfo
      - yasm
      - gcc-10
      - g++-10
      - clang-10
      - clang-format-10
      - clang-tidy-10
      - ninja-build
      - cppcheck
      - valgrind
      - doxygen
      - graphviz
      - lcov
  homebrew:
    packages:
      - automake
      - autoconf
      - autoconf-archive
      - libtool
      - texinfo
      - yasm
      - gcc
      - ninja
      - python
      - ccache
    update: true

os:
  - linux
  - osx

compiler:
  - g++-10
  - clang-10

jobs:
  fast_finish: true
  include:
    # Git Check
    - os: linux
      compiler: g++-10
      env: GITCHECK=true
      # Skip unnecessary steps since we aren't compiling
      before_install: skip
      install: skip
      script:
        - |
          if [[ -n $(git diff --check HEAD^) ]]; then
            echo "You must remove whitespace before submitting a pull request."
            echo ""
            git diff --check HEAD^
            exit -1
          else
            echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
          fi
      after_success: skip
    # Clang-format
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-10" CC="gcc-10"; fi
  - if [[ "$CXX" == "clang++" && "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="clang++-10" CC="clang-10"; fi

install:
  # vcpkg should be cached, but clone it if not
  - |
    if [[ ! -f vcpkg/vcpkg ]]; then
      git clone https://github.com/Microsoft/vcpkg.git
    fi
  - export VCPKG_ROOT="$TRAVIS_BUILD_DIR/vcpkg"
  - export PATH="$VCPKG_ROOT:$PATH"
  - cd $VCPKG_ROOT
  - git pull origin master --no-rebase
  - ./bootstrap-vcpkg.sh
  - vcpkg integrate install
  - rm -rf downloads buildtrees packages
  - cmake --version
  - cd ..
  - pwd
  # Install required libraries (these are often cached, so you must remove old dependencies first, as above)
  - travis_wait 60 vcpkg install --feature-flags=manifests

script:
  - cmake $CMAKE_ARGS -G Ninja -D CMAKE_BUILD_TYPE=Debug -S . -B build
  - travis_wait 60 cmake --build build

after_success:
  - cd build
  - travis_wait 60 ctest --output-on-failure