dist: bionic
sudo: required
virt: lxd
arch: s390x
services:
- docker
before_install:
#- sudo apt-get update
- cat /proc/sys/net/bridge/bridge-nf-call-iptables
- sudo apt install conntrack -y
- conntrack -L