
os: linux
dist: xenial
group: dev
language: shell
script:
- pyenv versions
- python -V
- which python
- pyenv install 3.7.2
- pyenv versions
- pyenv global 3.7.2
- pyenv versions
- python -V
- which python
