dist: bionic
sudo: required
#virt: lxd
arch: amd64
services:
- docker
before_install:
#- sudo apt-get update
- cat /proc/sys/net/bridge/bridge-nf-call-iptables
- sudo apt install conntrack -y
- sudo swapoff -a
- sudo conntrack -L
- route
- sudo sysctl net.ipv4.ip_forward
- route
- sudo apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common
- sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg |sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo add-apt-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
- sudo apt-get update
- sudo apt-get install -y kubelet kubeadm kubectl docker-ce
- sudo apt-mark hold kubelet kubeadm kubectl docker-ce
- kubeadm init --pod-network-cidr=10.244.0.0/16 --v=5  --ignore-preflight-errors=all --kubernetes-version=1.23.3
- sed -i 's/--network-plugin=cni //' /var/lib/kubelet/kubeadm-flags.env
- sudo systemctl daemon-reload
- sudo systemctl restart kubelet