jobs:
  - os: linux
    language: python
    python: 3.7
    dist: xenial
    #env:
      #- PYTHONPATH=.
    script:
      - python -V
      - python -m pip --version
      - pyenv install 3.7.10
      - pyenv global 3.7.10
      - python -V
      - python -m pip --version
      - pyenv versions
      - pip install -U pip