
os: linux
language: python
python: "3.7"
dist: xenial
script:
 - python -V
 - python -m pip --version
 - python -V
 - python -m pip --version
 - pyenv versions
 - pip install -U pip
 - pip3 install virtualenv
 - pip3 install awscli