language: java

jobs:
  include:
  - stage: job
    env: JDK=9 🚫
    script: source ./install-jdk.sh --verbose --feature 9

after_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}
- ls ${JAVA_HOME}
- java -version