
os: linux
dist: xenial
script:
- pyenv versions
- python -V
- pyenv global 3.7.1
- python -V
- printf "eval /"$(pyenv init --path)"/" >>~/.profile
- printf "eval /"$(pyenv init -)"/" >>~/.bashrc
- reset
- cat ~/.*profile
- cat ~/.*bashrc
- pyenv global 3.7.1
- python -V
