os: linux
dist: xenial

script:
# - sudo rm /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
# - sudo update-ca-certificates
- sydo apt install openssl ca-certificates wget
- sudo wget https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem
- sudo wget https://letsencrypt.org/certs/staging/letsencrypt-stg-root-dst.pem
- sudo cat letsencrypt-stg-root-x1.pem letsencrypt-stg-root-dst.pem >> ca.pem
- curl https://asset-packagist.org/packages.json
- curl https://get.rvm.io


