
os: linux
dist: xenial
script:
- pyenv install --list
- python -V
- pyenv global 3.7.1
- python -V
- echo "eval "$(pyenv init --path)"" >> ~/.*profile
- pyenv global 3.7.1
- cat ~/.*profile
- python -V
