language: python
python:
  - "3.7.3"

group: dev

install:

  - pip install .
  - pip install -r tests/requirements.txt

env:
- PYTHONPATH=.



# command to run tests
script:
  - python -m pip --version
  - python -m piptools --version
  - python -Werror tests/smoke_test.py
  - python -m unittest discover tests

