jobs:
  include:
    - os: linux
      node_js: '13'
      language: node_js
      dist: xenial
      script:
        - pyenv global 3.7.1
        - python -V
    - os: linux
      node_js: '13'
      language: node_js
      dist: opal
      script:
        - pyenv global 3.7.1
        - python -V
        - os: linux
      node_js: '13'
      language: node_js
      dist: stevonnie
      script:
        - pyenv global 3.7.1
        - python -V
    - os: linux
      node_js: '13'
      language: node_js
      dist: stevonnie
      script:
        - pyenv global 3.7.1
        - python -V
    - os: linux
      node_js: '13'
      language: node_js
      dist: bionic
      script:
        - pyenv global 3.7.1
        - python -V
    - os: linux
      node_js: '13'
      language: node_js
      dist: focal
      script:
        - pyenv global 3.7.2
        - python -V
