dist: focal
addons:
  rethinkdb: "2.4.1"
script:
- sudo apt-key adv --keyserver pgp.mit.edu --recv-keys "539A 3A8C 6692 E6E3 F69B 3FE8 1D85 E93F 801B B43F"
- echo -e "\ndeb https://download.rethinkdb.com/repository/ubuntu-$(lsb_release -cs)/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list > /dev/null'
- travis_apt_get_update
- package_version=`apt-cache show rethinkdb | grep -F \"Version":" "#{rethinkdb_version}\" | sort -r | head -n 1 | awk '{printf $2}'`"
- apt-get install -y -o Dpkg::Options::='--force-confnew' rethinkdb=$package_version"