
os: linux
dist: xenial
group: dev
script:
- pyenv versions
- python -V
- which python
- sed -Ei -e '/^([^#]|$)/ {a \
export PYENV_ROOT="$HOME/.pyenv"
a \
export PATH="$PYENV_ROOT/bin:$PATH"
a \
' -e ':a' -e '$!{n;ba};}' ~/.bash_profile
- echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
- echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
- echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
- echo 'eval "$(pyenv init --path)"' >> ~/.profile
- echo 'eval "$(pyenv init -)"' >> ~/.bashrc
- pyenv global 3.7.1
- python -V
- which python
