os: linux
dist: xenial

script:
- sudo apt update
- sudo apt install openssl ca-certificates
- sudo apt update ca-certificates
- curl https://asset-packagist.org/packages.json
- curl https://get.rvm.io


