dist: bionic
group: dev
sudo: true
script:
- wget https://travis-blue-public.s3.amazonaws.com/travis-worker-v6.2.16.snap
- snap install --dangerous ./travis-worker-v6.2.16.snap
- snap connect travis-worker:lxd lxd:lxd
- mv /root/worker.env /var/snap/travis-worker/common/