dist: bionic
group: dev
arch: amd64
jdk: openjdk16
script:
- java --version
- sudo apt-get install -y wget apt-transport-https
- wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo tee /usr/share/keyrings/adoptium.asc
- echo "deb [signed-by=/usr/share/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
- sudo apt-get update
- sudo apt-get install temurin-17-jdk --allow-unauthenticated
#- sudo update-java-alternatives -s "temurin-17-jdk-arm64"
#- export PATH=/usr/lib/jvm/temurin-8-jdk-arm64/bin:$PATH
- java --version
#- wget https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
#- tar xzf OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
#- export PATH=$PWD/jdk-16.0.2+7/bin:$PATH
#- java --version
